server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Aliissomeoneelse/Medicine-Market-Place.properties.git
          username: Aliissomeeoneelse
          password: ${git.password}
        default-label: dev/Alisher

#todo: http://localhost:8888/user-service-dev.yml